USE JOINS_PRACTICE;

SELECT * FROM TABLE1_FRUIT_BASKET;

-- INNER JOIN

SELECT T1.*, T2.*
FROM TABLE1_FRUIT_BASKET AS T1
INNER JOIN 
TABLE2_FRUIT_BASKET AS T2
ON T1.ID = T2.ID;

-- LEFT JOIN

SELECT T1.*, T2.*
FROM TABLE1_FRUIT_BASKET AS T1
LEFT JOIN TABLE2_FRUIT_BASKET AS T2
ON T1.ID = T2.ID;

-- RIGHT JOIN

SELECT T1.*, T2.*
FROM TABLE1_FRUIT_BASKET AS T1
RIGHT JOIN TABLE2_FRUIT_BASKET AS T2
ON T1.ID = T2.ID;

-- FULL OUTER JOIN EQUIVALENT 

SELECT T1.*, T2.*
FROM TABLE1_FRUIT_BASKET AS T1
LEFT JOIN TABLE2_FRUIT_BASKET AS T2
ON T1.ID = T2.ID

UNION

SELECT T1.*, T2.*
FROM TABLE1_FRUIT_BASKET AS T1
RIGHT JOIN TABLE2_FRUIT_BASKET AS T2
ON T1.ID = T2.ID;

-- CROSS JOIN

SELECT T1.*, T2.*
FROM TABLE1_FRUIT_BASKET AS T1
CROSS JOIN TABLE2_FRUIT_BASKET AS T2;

-- SELF JOIN

SELECT E1.NAME AS Employee_name, E2.NAME AS Manager_name
FROM Employee as e1
INNER JOIN Employee as e2
ON e1.managerID = e2.EmployeeID;

-- UNION ALL
-- aliases used on select rows to rename the columns in the results:

SELECT t1.ID AS T1ID, T1.Fruit AS T1FRUIT
FROM TABLE1_FRUIT_BASKET AS T1

UNION ALL 

SELECT T2.ID AS T2ID, T2.Fruit AS T2FRUIT
FROM TABLE2_FRUIT_BASKET AS T2;

-- UNION

SELECT t1.ID AS T1ID, T1.Fruit AS T1FRUIT
FROM TABLE1_FRUIT_BASKET AS T1

UNION 

SELECT T2.ID AS T2ID, T2.Fruit AS T2FRUIT
FROM TABLE2_FRUIT_BASKET AS T2;




